//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheremetevSeregin
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int id_registration { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string age { get; set; }
    }
}
